apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: eric-sc
