apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: eric-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eric-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: eric-sc
---

apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-container
      image: alpine
      command: ["/bin/sh", "-c"]
      args: [ "hostname >> /opt/myhostnames ; sleep 60" ]
      volumeMounts:
        - name: eric-pvc
          mountPath: /opt/myhostnames
  volumes:
    - name: eric-pvc
      persistentVolumeClaim:
        claimName: eric-pvc
