apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: cXdlcnR5dWlvcA==
---
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb-eric
spec:
  containers:
  - name: mysqldb-eric
    image: mysql:5.6
    ports:
    - containerPort: 80
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-pass
            key: password
